services:
  servidor:
    container_name: Flask
    build:
      context: Flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      SMARTFEELINGS_DATABASE_URI: postgresql://rnsibxkn:glTdKMCJR9PMpTrmlEtrpMJW2StbFzBc@tuffi.db.elephantsql.com/rnsibxkn
      SMARTFEELINGS_JWT_SECRET: smartfeelings-123
      TWITTER_API_KEY: bijvj1aSez55Uc05T6n2TAMTt
      TWITTER_API_KEY_SECRET: 5IYVIhMw12uNhej1L3v4jyFCLMCL3UQ62DNjewfEgu8e2yaCLz
      TWITTER_BEARER_TOKEN: AAAAAAAAAAAAAAAAAAAAANn1awEAAAAAiZEjSkESGs7LdD8Jc0jaJxPMPmo%3DYQtmaiyfhgtuQHsphthoyfvGlMjXp4orBRx1oMX0sRYl50paOz
      PAGE2API_API_KEY: 2535b8f7f9691475991f9de139c0453615fd4a3e
    depends_on: 
      - db   
    networks: 
      - backend
      - frontend
  db:
    container_name: PostgreSQL
    image: 'postgres:13.4-alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=smartfeelings
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - backend  
volumes:
  db-data:

networks:
  backend:
  frontend:  